### ISSUE TITLE
no such column: raw_string_jid

### ISSUE THREAD

**Issue by sambeta01** [abdeladim-s/whatsapp-msgstore-viewer#6]
It seems that after hours of research, which led me eventually to ElDavoo, I was able to decrypt the db.crypt15, only to find it is useless!
Please help!

**Comment by abdeladim-s** [comment]
@sambeta01, if you successfully decrypted the db then you are half way through. I think the problem is that they updated the db schema and hat's why you are getting no such column. 
I described the steps to create your own db adapter in the [Notes section](https://github.com/abdeladim-s/whatsapp-msgstore-viewer#about-the-database-schema).

**Comment by sambeta01** [comment]
there appear to be too many changes for my low expertise in SQL to handle, I’ve attached the db [schema.txt](https://github.com/user-attachments/files/17322087/schema.txt), hoping you could help us who are using WhatsApp v2.24.19.86.
Furthermore, it would be very helpful, to enrich the code with comments about each table/column you are referring to. 
Also, if you could update the schema once or twice a year, while keeping all dbs’ schemas (using WhatsApp version and/or date instead of v1, v2…), it would make this project best there is.

**Comment by abdeladim-s** [comment]
* With just the schema, I don't think I can help unfortunately. It's a reverse engineering process that requires a lot of trial and error.
* Also, I don't have the time or resources to keep up with every WhatsApp update. I took the first step by releasing the project as open source, but without help from others, I can't do everything alone.
* As for the comments, every function is already documented in the [abstract class](https://github.com/abdeladim-s/whatsapp-msgstore-viewer/blob/ea59b4b9dfde3db902db52f823165e653faeaaf6/dbs/abstract_db.py#L16), nd you can see how I implemented them for my database in v1.
* Yes, the idea is to keep all the database schemas. Naming it with the WhatsApp version is a great idea. I don't remember which version of WhatsApp I used at the time, but I'll try to include the version for future contributions.

**Comment by sambeta01** [comment]
I was able to do it after doing the following:
1- changed all "raw_string_jid" to "jid.raw_string" everywhere.
2- as the new above table type is now INT, I changed line 79 in \View\MainScreen\main_screen.py to: chatitem.jid = str(chat['jid_row_id'])

**Comment by abdeladim-s** [comment]
would be great if you submitted a PR with your changes to help others in the same situation as you.
