### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by sambeta01** [abdeladim-s/whatsapp-msgstore-viewer#7]
Messages with RTL languages are not displayed correctly, even with supported font.
Messages are not ordered, should be ordered chronologically.
Lack of search.

**Comment by abdeladim-s** [comment]
* unfortunately it's a kivy issue, it does not support RTL, I didn't knew it until I finished the project! but take a look at [this](https://github.com/kivy/kivy/issues/8001) and the other issues there, some people were able to use it with resharper. 
* Check you sql query, you can fetch them in the order you want!

**Comment by sambeta01** [comment]
unfortunately the method with resharper won't work with RTL/LTR languagaes are mixed. any suggestion?
for the chronological order, I added 'order by timestamp desc' to line 65 in db.py. I believe this should be included in the main code as everyone who is using WhatsApp is familiar with this ordering.
what about search?

**Comment by abdeladim-s** [comment]
* rReSharper supports RTL languages, but when languages are mixed, I'm honestly not sure how it handles that. It's unfortunate that Kivy, despite being so mature, still doesn't support international languages.
* True, ordering by timestamp is the standard approach, but it wasn't what I needed for my use case. Feel free to submit a PR, and I'll be happy to merge it.
* For the search, I think it's doable, it's just another sql query .. but I need time to implement it, will look into that when I get some free time.

**Comment by sambeta01** [comment]
Kivy does not look like it will support RTL languages anytime soon, as it requires some high caliber developers, who are also native RTL speakers, as no one else is motivated.
